name: Archivar Server TEST
on:
  schedule:
    - cron: '15 14 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: API Clouding Archive
        run: |
          curl -i -X POST "https://api.clouding.io/v1/servers/${{ secrets.SERVER_ID }}/archive" \
          -H "X-API-KEY: ${{ secrets.CLOUDING_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d ''